create table if not exists public.user_roles (user_id uuid primary key references auth.users(id) on delete cascade, role text not null default 'member' check (role in ('admin','member')), created_at timestamptz not null default now());
create table if not exists public.career_profiles (user_id uuid primary key references auth.users(id) on delete cascade, objective text not null default '', education text not null default '', experience text not null default '', skills text not null default '', updated_at timestamptz not null default now());
create table if not exists public.portfolio_projects (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, description text not null default '', project_url text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.user_roles enable row level security; alter table public.career_profiles enable row level security; alter table public.portfolio_projects enable row level security;
grant select on public.user_roles to authenticated; grant select,insert,update,delete on public.career_profiles,public.portfolio_projects to authenticated;
drop policy if exists "roles_read_own" on public.user_roles;
drop policy if exists "career_manage_own" on public.career_profiles;
drop policy if exists "portfolio_manage_own" on public.portfolio_projects;
create policy "roles_read_own" on public.user_roles for select to authenticated using ((select auth.uid())=user_id);
create policy "career_manage_own" on public.career_profiles for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "portfolio_manage_own" on public.portfolio_projects for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create or replace function public.is_admin() returns boolean language sql security definer stable set search_path='' as $$ select exists(select 1 from public.user_roles where user_id=(select auth.uid()) and role='admin'); $$;
grant execute on function public.is_admin() to authenticated;
drop policy if exists "admin_manage_tracks" on public.tracks;
drop policy if exists "admin_manage_lessons" on public.lessons;
drop policy if exists "admin_manage_opportunities" on public.opportunities;
create policy "admin_manage_tracks" on public.tracks for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "admin_manage_lessons" on public.lessons for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "admin_manage_opportunities" on public.opportunities for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
grant insert,update,delete on public.tracks,public.lessons,public.opportunities to authenticated;
create or replace function public.delete_own_account(confirmation text) returns void language plpgsql security definer set search_path='' as $$ begin if confirmation<>'EXCLUIR' or (select auth.uid()) is null then raise exception 'Confirmação inválida'; end if; delete from auth.users where id=(select auth.uid()); end; $$;
revoke all on function public.delete_own_account(text) from public; grant execute on function public.delete_own_account(text) to authenticated;
